week1: [{
    "_id": ObjectId(""),
    "weekName": "Monday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Tuesday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Wedenseday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Thursday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Friday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
]




week2: [{
    "_id": ObjectId(""),
    "weekName": "Monday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Tuesday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Wedneseday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Thursday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
{
    "_id": ObjectId(""),
    "weekName": "Friday",
    "date": "",
    "interior": 0,
    "exterior": 0,
    "fiberglassSteel": 0,
    "cuts": 0,
    "commercial": 0,
},
]