week1: [{
    "_id": ObjectId(""),
    "weekName": "Monday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Tuesday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Wednseday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Thursday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Friday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
]




week2: [{
    "_id": ObjectId(""),
    "weekName": "Monday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Tuesday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Wednseday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Thursday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
{
    "_id": ObjectId(""),
    "weekName": "Friday",
    "date": "",
    "interior": [],
    "exterior": [],
    "fiberglassSteel": [],
    "cuts": [],
    "commercial": [],
},
]